# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestEnterAccount40:
    @pytest.fixture(autouse=True)
    def setup_teardown(self):
        self.driver = webdriver.Chrome()
        self.vars = {}
        yield
        self.driver.quit()

    def test_enterAccount40(self):
        self.driver.get("https://comfy.ua/")
        self.driver.set_window_size(1552, 849)
        element = self.driver.find_element(By.LINK_TEXT, "Войти")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".header-bottom-profile__link > span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".header-bottom-profile__link > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.XPATH, "//div[3]/div/div/input").click()
        self.driver.find_element(By.XPATH, "//div[3]/div/div/input").send_keys("+38(098)-502-92-04")
        self.driver.find_element(By.CSS_SELECTOR, ".cmf-button-primary__text").click()