# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait

class TestQwerty():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_qwerty(self):
    self.driver.get("https://www.easemytrip.com/")
    self.driver.set_window_size(1536, 836)
    self.driver.find_element(By.ID, "FromSector_show").click()
    self.driver.find_element(By.ID, "a_FromSector_show").send_keys("d")
    self.driver.find_element(By.CSS_SELECTOR, ".ausuggest:nth-child(3) > li:nth-child(1) div:nth-child(2)").click()
    self.driver.find_element(By.ID, "a_Editbox13_show").send_keys("ist")
    WebDriverWait(self.driver, 60).until(
        EC.presence_of_element_located((By.XPATH, "//span[@id=\'spnIstanbul \']")))
    self.driver.find_element(By.XPATH, "//span[@id=\'spnIstanbul \']").click()
    WebDriverWait(self.driver, 30).until(
        EC.presence_of_element_located((By.XPATH,"//li[@id=\'fiv_2_28/11/2023\']")))
    self.driver.find_element(By.XPATH, "//li[@id=\'fiv_2_28/11/2023\']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".srchBtnSe").click()
    WebDriverWait(self.driver, 100).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, ".lis")))
    found_flights_count = self.driver.find_elements(By.CSS_SELECTOR, ".lis")
    print(f"Знайдено рейсів: {len(found_flights_count)}")
if __name__ == "__main__":
  test_instance = TestQwerty()
  test_instance.setup_method(None)
  test_instance.test_qwerty()
  test_instance.teardown_method(None)